// applicationserver/libs package implements a application server (AppServer), so 
// that frontend server can fetch processed data from this server. This server 
// provides following RPCs:
// 
// * Register - registration of a service user.
// * Login - Logging in a already registered user through credentials validation.
// * UserID - provides the user id of registered user.
// * UpdateFoodTruck - updates a registered user's food truck location status.
// * CloseFoodTruck - closes down the service of a food truck.
// * FindNearest - Finds the nearest available food truck of a particular location.
//
// An instance of this AppServer can be generated by calling New() method and to 
// start the server, it needs to call blocked Start() method of Appserver instance.

package libs

import (
	"fmt"
	"log"
	"strconv"
	"net"
	"net/rpc"

	"common"
)

type AppServer struct {
	uDbMgr common.UserDbManager
    ftDbClient *rpc.Client
}

// New returns an instance of AppServer class. To instantiate this server, an 
// implementation of UserDbManager interface (common/data_manager_interface.go)
// and a rpc client of Food Truck database server needs to be passed through 
// function argument.
func New(uDbM common.UserDbManager, client *rpc.Client) *AppServer {
	return &AppServer{
		uDbMgr: uDbM,
		ftDbClient: client,
	}
}

// Start starts the AppServer by opening the tcp port. It's a blocked method,
// so it should be called from a seperate goroutine,
func (srv *AppServer) Start(port int) {
	fmt.Println("Application server starting ...")
	rpc.Register(srv)
	
	fmt.Println("Application server opening tcp port ...")
	l, err := net.Listen("tcp", ":" + strconv.Itoa(port))
	if err != nil {
		log.Fatal("listen error:", err)
	}
	fmt.Println("Application server successfully started ...")
	rpc.Accept(l)
}

// All application server RPC methods definition.

func (srv *AppServer) Register(ud *common.UserData, ID *int64) error {
	*ID = srv.uDbMgr.AddUser(ud.Name, ud.Pw, ud.Cuisine)
	return nil
}

func (srv *AppServer) Login(ud *common.UserData, ok *bool) error {
	*ok = srv.uDbMgr.ValidateUser(ud.Name, ud.Pw)
	return nil
}

func (srv *AppServer) UserID(ud *common.UserData, ID *int64) error {
	*ID = srv.uDbMgr.UserID(ud.Name)
	return nil
}

func (srv *AppServer) UpdateFoodTruck(td *common.TruckData, ok *bool) error {
	err := srv.ftDbClient.Call("FTServer.UpdateFoodTruck", td, ok)
	if err != nil {
		return err
	}
	return nil
}

func (srv *AppServer) CloseFoodTruck(td *common.TruckData, ok *bool) error {
	err := srv.ftDbClient.Call("FTServer.CloseFoodTruck", td, ok)
	if err != nil {
		return err
	}
	return nil
}

func (srv *AppServer) FindNearest(td *common.Location, res *[]*common.TruckData) error {
	err := srv.ftDbClient.Call("FTServer.FindNearestFoodTruck", td, res)
	if err != nil {
		return err
	}
	return nil
}

