runtime: go
env: flex

env_variables:
  CLOUDSQL_CONNECTION_NAME: 'foodtruckapplication-175305:europe-west1:database'
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: '10891089'
  
beta_settings:
    cloud_sql_instances: 'foodtruckapplication-175305:europe-west1:database'