runtime: go
env: flex

env_variables:
  # Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
  # Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
  # For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
  CLOUDSQL_CONNECTION_NAME: 'foodtruckapplication-175305:europe-west1:userdb'
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: '10891089'